// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.edgb.aviationclubmanager.domain;

import de.edgb.aviationclubmanager.domain.Accounting;

privileged aspect Accounting_Roo_JavaBean {
    
    public String Accounting.getName() {
        return this.name;
    }
    
    public void Accounting.setName(String name) {
        this.name = name;
    }
    
}
