// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.edgb.aviationclubmanager.domain;

import de.edgb.aviationclubmanager.domain.ClubMember;
import javax.persistence.Entity;

privileged aspect ClubMember_Roo_Jpa_Entity {
    
    declare @type: ClubMember: @Entity;
    
}
