// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.edgb.aviationclubmanager.domain;

import de.edgb.aviationclubmanager.domain.ClubCapacity;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ClubCapacity_Roo_Configurable {
    
    declare @type: ClubCapacity: @Configurable;
    
}
