// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package de.edgb.aviationclubmanager.domain;

import de.edgb.aviationclubmanager.domain.UserPermission;

privileged aspect UserPermission_Roo_JavaBean {
    
    public String UserPermission.getName() {
        return this.name;
    }
    
    public void UserPermission.setName(String name) {
        this.name = name;
    }
    
}
